### ISSUE TITLE
Bug with float128 and not with float64?

### ISSUE THREAD

**Issue by doronbehar** [cjekel/piecewise_linear_fit_py#119]
The following MWE:

```
from pwlf import PiecewiseLinFit
import numpy as np

fit = PiecewiseLinFit(np.linspace(0, 10, dtype=np.float128), np.random.random(50))
fit.fit(2)
fit.p_values()
```

Errors for me with:

```
Traceback (most recent call last):
  File "/home/doron/repos/lab-ion-trap-simulations/./pwfit_float128_bug.py", line 8, in <module>
    print(fit.p_values())
          ^^^^^^^^^^^^^^
  File "/nix/store/8p528p5cji81aidpbpwiyyz5s9nb1lz4-python3-3.12.8-env/lib/python3.12/site-packages/pwlf/pwlf.py", line 1484, in p_values
    p = 2.0 * stats.t.sf(np.abs(t), df=n - k - 1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8p528p5cji81aidpbpwiyyz5s9nb1lz4-python3-3.12.8-env/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 2203, in sf
    place(output, cond, self._sf(*goodargs))
                        ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8p528p5cji81aidpbpwiyyz5s9nb1lz4-python3-3.12.8-env/lib/python3.12/site-packages/scipy/stats/_continuous_distns.py", line 7716, in _sf
    return sc.stdtr(df, -x)
           ^^^^^^^^^^^^^^^^
TypeError: ufunc 'stdtr' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

However, without the `dtype=np.float64`, no error.

**Comment by cjekel** [comment]
@doronbehar thank you for the simple reproducer.

It looks like scipy does not fully support float128, and many of the scipy.stats methods are float64 only (e.g. `scipy.stats.t.sf`).

How would you like this calculation to work?

I could cast down to float64 to get an answer? 

I just added smoke tests for float32 and float128 support due to this https://github.com/cjekel/piecewise_linear_fit_py/commit/ba767916c7321a368c8fc4aeafdc7070416ab7f1

**Comment by doronbehar** [comment]
Hmm maybe create a MWE for scipy and create a bug report there? Untill that will be solved, we can downcast to float64 in pwlf...

**Comment by cjekel** [comment]
here  is a scipy reproducer
```python
import numpy as np
import scipy
scipy.stats.t.sf(np.random.random(3).astype(np.float128), df=3)
```

**Comment by doronbehar** [comment]
Hmm I wonder if scipy devs will simply reply to this: "What do you want, the error message explicitly states that this input type is not supported". Maybe pwlf should simply downcast floats 128 to floats 64?

**Comment by doronbehar** [comment]
Or on a 2nd thought, perhaps Scipy should downcast floats 128 to floats 64 with a warning instead of failing.
