### ISSUE TITLE
Implement not-so rudimentary support of version string

### ISSUE THREAD

**Issue by lstolcman** [cjekel/piecewise_linear_fit_py#53]
Hi

I am using pwlf within https://github.com/pyinstaller/pyinstaller (it compiles python to exe on windows).

However, pwlf is causing some troubles, because version handling is too simple - the file "https://github.com/cjekel/piecewise_linear_fit_py/blob/master/pwlf/VERSION" is not included automatically in the build, and I have to create it every time. Otherwise, it is failing:
https://github.com/cjekel/piecewise_linear_fit_py/blob/8f974440c25cf6b57c1af50dfd4f3d5f7ab3ac73/pwlf/__init__.py#L11-L12

For now I'm going to generate empty VERSION file by script, however it is not a solution.

I suggest to use the approach numpy guys use:
They generate version.py file by setup.py:
https://github.com/numpy/numpy/blob/96abdedcb21df7e1a07a7e73a5f2103895a36faf/setup.py#L127

and then import it as `__version__`:
https://github.com/numpy/numpy/blob/b7c27bd2a3817f59c84b004b87bba5db57d9a9b0/numpy/__init__.py#L132

**Comment by cjekel** [comment]
Thanks for making this issue and offering a suggestion. I've never used pyinstaller, but it looks interesting.

The numpy solution seems to be bringing out the big tools.

Is there an easier way that will work for your case? Like just expressing the version as a string in __init__ or setup?

**Comment by cjekel** [comment]
Perhaps scikit-learn style versioning?

**Comment by cjekel** [comment]
I think I'm going to go with the setuptools style versioning. https://github.com/pypa/setuptools/blob/master/setuptools/version.py which is number 5 from [this](https://packaging.python.org/guides/single-sourcing-package-version/) list.

see PR https://github.com/cjekel/piecewise_linear_fit_py/pull/57 which I've tested to work with pyinstaller

I'll probably merge this in soon

**Comment by cjekel** [comment]
I'll let you close this, but whenever you get a chance let me know if the latest version fixes your pyinstaller issue.

**Comment by lstolcman** [comment]
@cjekel the patch solved the problem, thank you

**Comment by AetherPrior** [comment]
Hello, I know it has been a while, but a similar issue on pyinstaller with pwlf has risen for me:
This time, there seems to be something wrong with importlib-metadata not finding pwlf:
```
Traceback (most recent call last):
  File "Project\helper_script.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\l\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "Project\Tensile\tensile_gui.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\l\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "Project\utils\image_ret.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\l\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "Project\utils\helper.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\l\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pwlf\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\l\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pwlf\version.py", line 7, in <module>
  File "site-packages\importlib_metadata\__init__.py", line 576, in version
  File "site-packages\importlib_metadata\__init__.py", line 549, in distribution
  File "site-packages\importlib_metadata\__init__.py", line 206, in from_name
importlib_metadata.PackageNotFoundError: pwlf
```
did this issue crop up again by any chance @lstolcman ?

**Comment by cjekel** [comment]
@AetherPrior Can you report if the [simple-version](https://github.com/cjekel/piecewise_linear_fit_py/tree/simple-version) branch happens to fix your problem?

**Comment by AetherPrior** [comment]
@cjekel it did fix this problem. Another problem from another library surfaced, but I don't think it's related to this one.

**Comment by cjekel** [comment]
Okay, thanks! I'll push a new release soon.
